POST http://localhost:3000/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "id": "d874e42d-70b3-4390-b050-4535c7cf8fb1",
  "date": "2017-08-12",
  "type": "Hospital",
  "specialist": "MD House",
  "diagnosisCodes": ["S62.5"],
  "description":
    "Healing time appr. 2 weeks. patient doesn't remember how he got the injury.",
  "discharge": {
    "date": "2017-08-26",
    "criteria": "Thumb has healed."
  }
}
