require("dotenv").config()

const ENVIRONMENT_CLASS = process.env.NODE_ENV
const IS_TEST_ENVIRONMENT = ENVIRONMENT_CLASS === "test"

const PORT_TO_LISTEN = process.env.PORT

const MONGO_USER_NAME = IS_TEST_ENVIRONMENT
  ? process.env.TEST_MONGO_USER_NAME
  : process.env.MONGO_USER_NAME

const MONGO_PASSWORD = IS_TEST_ENVIRONMENT
  ? process.env.TEST_MONGO_PASSWORD
  : process.env.MONGO_PASSWORD

const MONGO_CLUSTER_NAME = IS_TEST_ENVIRONMENT
  ? process.env.TEST_MONGO_CLUSTER_NAME
  : process.env.MONGO_CLUSTER_NAME

const MONGO_DATABASE_NAME = IS_TEST_ENVIRONMENT
  ? process.env.TEST_MONGO_DATABASE_NAME
  : process.env.MONGO_DATABASE_NAME

const URL_BASE = "/"
const URL_API_ROOT = URL_BASE + "api/"
const URL_API_BLOGS = URL_API_ROOT + "blogs"

const EXIT_CODE_FAILURE = 1

const HTTP_STATUS_OK = 200
const HTTP_STATUS_CREATED = 201
const HTTP_STATUS_NO_CONTENT = 204
const HTTP_STATUS_BAD_REQUEST = 400
const HTTP_STATUS_NOT_FOUND = 404
const HTTP_STATUS_INTERNAL_SERVER_ERROR = 500

module.exports = {
  ENVIRONMENT_CLASS,
  IS_TEST_ENVIRONMENT,

  PORT_TO_LISTEN,

  MONGO_USER_NAME,
  MONGO_PASSWORD,
  MONGO_CLUSTER_NAME,
  MONGO_DATABASE_NAME,

  URL_BASE,
  URL_API_ROOT,
  URL_API_BLOGS,

  EXIT_CODE_FAILURE,

  HTTP_STATUS_OK,
  HTTP_STATUS_CREATED,
  HTTP_STATUS_NO_CONTENT,
  HTTP_STATUS_BAD_REQUEST,
  HTTP_STATUS_NOT_FOUND,
  HTTP_STATUS_INTERNAL_SERVER_ERROR,
}